POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic client-id-test:client-id-secret

grant_type=password&username=user1&password=password

###

GET http://localhost:8080/

###

GET http://localhost:8080/api/game/next_turn
Authorization: Bearer 9aef06ff-51c4-4b11-9ce3-79289ad22094

###

GET http://localhost:8080/api/admin/users
Authorization: Bearer 3dbde7f3-d8c9-4a7e-835b-f2dafa227e8b

###

GET http://localhost:8080/api/admin/users/2
Authorization: Bearer 3dbde7f3-d8c9-4a7e-835b-f2dafa227e8b

###


GET http://localhost:8080/api/movies/tt0000001
Authorization: Bearer f93ccb78-9364-4677-92d3-44348c67353f
###

GET http://localhost:8080/api/movies/tt1773696
Authorization: Bearer 2471fdb1-4442-4c99-aba2-d5f90401c579

###

GET http://localhost:8080/api/movies/tt0083658
Authorization: Bearer 2471fdb1-4442-4c99-aba2-d5f90401c579

###

GET http://localhost:8080/api/movies?title=star
Authorization: Bearer e5ab606a-7292-417e-a6a0-5e9669aa0115

###
POST http://localhost:8080/api/admin/users
Authorization: Bearer 3dbde7f3-d8c9-4a7e-835b-f2dafa227e8b
Content-Type: application/json

{
    "username": "thiagoaguiar",
    "name": "Thiago Aguiar",
    "email": "thi@go.pro.br",
    "password": "password"
}


###

GET http://www.omdbapi.com/?apikey=3a2f3429&t=star war

###

GET http://www.omdbapi.com/?t=start